// ~Restore BG1 Item Icons and Appearance~
// Weapons DESIGNATED 50 LABEL "ac-bg-icons-colors"

  // AXES
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h02.itm~) THEN BEGIN
COPY_EXISTING ~ax1h02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 94		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 18	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h03.itm~) THEN BEGIN
COPY_EXISTING ~ax1h03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h04.itm~) THEN BEGIN
COPY_EXISTING ~ax1h04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 41	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h05.itm~) THEN BEGIN
COPY_EXISTING ~ax1h05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h07.itm~) THEN BEGIN
COPY_EXISTING ~ax1h07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h08.itm~) THEN BEGIN
COPY_EXISTING ~ax1h08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h09.itm~) THEN BEGIN
COPY_EXISTING ~ax1h09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h10.itm~) THEN BEGIN
COPY_EXISTING ~ax1h10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 255
	SET setg = 76
	SET setb = 106
	SET speed = 0x14
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 255
	SET setg = 76
	SET setb = 106
	SET speed = 0x14
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 255
	SET setg = 76
	SET setb = 106
	SET speed = 0x14
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 101		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 101	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 101	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h11.itm~) THEN BEGIN
COPY_EXISTING ~ax1h11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 110		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 110	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h12.itm~) THEN BEGIN
COPY_EXISTING ~ax1h12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 72		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 72	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 72	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h13.itm~) THEN BEGIN
COPY_EXISTING ~ax1h13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h14.itm~) THEN BEGIN
COPY_EXISTING ~ax1h14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 98	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h15.itm~) THEN BEGIN
COPY_EXISTING ~ax1h15.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 159
	SET setb = 253
	SET speed = 0x1e
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h16.itm~) THEN BEGIN
COPY_EXISTING ~ax1h16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ax1h16.itm~) THEN BEGIN
COPY_EXISTING ~ax1h16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // BLUNT WEAPONS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun01.itm~) THEN BEGIN
COPY_EXISTING ~blun01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 22		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun03.itm~) THEN BEGIN
COPY_EXISTING ~blun03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun05.itm~) THEN BEGIN
COPY_EXISTING ~blun05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 38	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun08.itm~) THEN BEGIN
COPY_EXISTING ~blun08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 104		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 21	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun09.itm~) THEN BEGIN
COPY_EXISTING ~blun09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 8		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 4	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 4	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun10.itm~) THEN BEGIN
COPY_EXISTING ~blun10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 22		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun12.itm~) THEN BEGIN
COPY_EXISTING ~blun12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun13.itm~) THEN BEGIN
COPY_EXISTING ~blun13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14.itm~) THEN BEGIN
COPY_EXISTING ~blun14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 229
	SET setg = 215
	SET setb = 83
	SET speed = 0x64
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14d.itm~) THEN BEGIN
COPY_EXISTING ~blun14d.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14e.itm~) THEN BEGIN
COPY_EXISTING ~blun14e.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14f.itm~) THEN BEGIN
COPY_EXISTING ~blun14f.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14g.itm~) THEN BEGIN
COPY_EXISTING ~blun14g.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14h.itm~) THEN BEGIN
COPY_EXISTING ~blun14h.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun14i.itm~) THEN BEGIN
COPY_EXISTING ~blun14i.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun16.itm~) THEN BEGIN
COPY_EXISTING ~blun16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun17.itm~) THEN BEGIN
COPY_EXISTING ~blun17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 7		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 7	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 7	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun18.itm~) THEN BEGIN
COPY_EXISTING ~blun18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 28		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun19.itm~) THEN BEGIN
COPY_EXISTING ~blun19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 38	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun20.itm~) THEN BEGIN
COPY_EXISTING ~blun20.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 24		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 24	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 24	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun22.itm~) THEN BEGIN
COPY_EXISTING ~blun22.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 47		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun22.itm~) THEN BEGIN
COPY_EXISTING ~blun22.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 47		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun23.itm~) THEN BEGIN
COPY_EXISTING ~blun23.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 10		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun23.itm~) THEN BEGIN
COPY_EXISTING ~blun23.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 10		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun24.itm~) THEN BEGIN
COPY_EXISTING ~blun24.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 22		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun25.itm~) THEN BEGIN
COPY_EXISTING ~blun25.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 38	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun26.itm~) THEN BEGIN
COPY_EXISTING ~blun26.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 6		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 92	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 6	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun27.itm~) THEN BEGIN
COPY_EXISTING ~blun27.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 91	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun30.itm~) THEN BEGIN
COPY_EXISTING ~blun30.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 229
	SET setg = 215
	SET setb = 83
	SET speed = 0x64
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun30c.itm~) THEN BEGIN
COPY_EXISTING ~blun30c.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 229
	SET setg = 215
	SET setb = 83
	SET speed = 0x64
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~blun30d.itm~) THEN BEGIN
COPY_EXISTING ~blun30d.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 229
	SET setg = 215
	SET setb = 83
	SET speed = 0x64
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	 	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // BOWS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow01.itm~) THEN BEGIN
COPY_EXISTING ~bow01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 85		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow02.itm~) THEN BEGIN
COPY_EXISTING ~bow02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 13	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow03.itm~) THEN BEGIN
COPY_EXISTING ~bow03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow04.itm~) THEN BEGIN
COPY_EXISTING ~bow04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 65		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 65	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow05.itm~) THEN BEGIN
COPY_EXISTING ~bow05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow06.itm~) THEN BEGIN
COPY_EXISTING ~bow06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 75		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow07.itm~) THEN BEGIN
COPY_EXISTING ~bow07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 61		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 61	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow08.itm~) THEN BEGIN
COPY_EXISTING ~bow08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 59	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow09.itm~) THEN BEGIN
COPY_EXISTING ~bow08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 19	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow10.itm~) THEN BEGIN
COPY_EXISTING ~bow10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 35	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow11.itm~) THEN BEGIN
COPY_EXISTING ~bow11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow12.itm~) THEN BEGIN
COPY_EXISTING ~bow12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 65		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 103	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow13.itm~) THEN BEGIN
COPY_EXISTING ~bow13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 65		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow14.itm~) THEN BEGIN
COPY_EXISTING ~bow14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 75		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow15.itm~) THEN BEGIN
COPY_EXISTING ~bow15.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 75		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 19	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow16.itm~) THEN BEGIN
COPY_EXISTING ~bow16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 38	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow17.itm~) THEN BEGIN
COPY_EXISTING ~bow17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 65		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow18.itm~) THEN BEGIN
COPY_EXISTING ~bow18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 75		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow19.itm~) THEN BEGIN
COPY_EXISTING ~bow19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 14		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow20.itm~) THEN BEGIN
COPY_EXISTING ~bow20.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 49		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow21.itm~) THEN BEGIN
COPY_EXISTING ~bow21.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 49		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow22.itm~) THEN BEGIN
COPY_EXISTING ~bow22.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 65		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow23.itm~) THEN BEGIN
COPY_EXISTING ~bow23.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 65		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow24.itm~) THEN BEGIN
COPY_EXISTING ~bow24.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 42		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow25.itm~) THEN BEGIN
COPY_EXISTING ~bow25.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 49		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bow26.itm~) THEN BEGIN
COPY_EXISTING ~bow26.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 46		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 58	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~compb05.itm~) THEN BEGIN
COPY_EXISTING ~compb05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~compb06.itm~) THEN BEGIN
COPY_EXISTING ~compb06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 75		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~compb08.itm~) THEN BEGIN
COPY_EXISTING ~compb08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 13		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 59	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // CLOAKS AND ROBES
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~clck21.itm~) THEN BEGIN
COPY_EXISTING ~clck21.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~iclck21~
	WRITE_LONG  0x5C 0
    WRITE_ASCII 0x58 ~cclck06~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~wa2robe.itm~) THEN BEGIN
COPY_EXISTING ~wa2robe.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 29		// colour index
	SET location = agrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 34	// colour index
	SET location = ared		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 32	// colour index
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // DAGGERS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg01.itm~) THEN BEGIN
COPY_EXISTING ~dagg01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg02.itm~) THEN BEGIN
COPY_EXISTING ~dagg02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg03.itm~) THEN BEGIN
COPY_EXISTING ~dagg03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg04.itm~) THEN BEGIN
COPY_EXISTING ~dagg04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 57
	SET setb = 63
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 57
	SET setb = 63
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 57
	SET setb = 63
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 5		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 63	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg05.itm~) THEN BEGIN
COPY_EXISTING ~dagg05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg06.itm~) THEN BEGIN
COPY_EXISTING ~dagg06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg07.itm~) THEN BEGIN
COPY_EXISTING ~dagg07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg08.itm~) THEN BEGIN
COPY_EXISTING ~dagg08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg09.itm~) THEN BEGIN
COPY_EXISTING ~dagg09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg10.itm~) THEN BEGIN
COPY_EXISTING ~dagg10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg11.itm~) THEN BEGIN
COPY_EXISTING ~dagg11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg12.itm~) THEN BEGIN
COPY_EXISTING ~dagg12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 242
	SET setg = 152
	SET setb = 189
	SET speed = 0x78
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 47		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg13.itm~) THEN BEGIN
COPY_EXISTING ~dagg13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg14.itm~) THEN BEGIN
COPY_EXISTING ~dagg14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg15.itm~) THEN BEGIN
COPY_EXISTING ~dagg15.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 66	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg16.itm~) THEN BEGIN
COPY_EXISTING ~dagg16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 32		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 32	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 32	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg17.itm~) THEN BEGIN
COPY_EXISTING ~dagg17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg18.itm~) THEN BEGIN
COPY_EXISTING ~dagg18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg19.itm~) THEN BEGIN
COPY_EXISTING ~dagg19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 91	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg20.itm~) THEN BEGIN
COPY_EXISTING ~dagg20.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg21.itm~) THEN BEGIN
COPY_EXISTING ~dagg21.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 46	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 17	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg22.itm~) THEN BEGIN
COPY_EXISTING ~dagg22.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 46	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 17	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg23.itm~) THEN BEGIN
COPY_EXISTING ~dagg23.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 93		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 46	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~dagg24.itm~) THEN BEGIN
COPY_EXISTING ~dagg24.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 50		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~daggshit.itm~) THEN BEGIN
COPY_EXISTING ~daggshit.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // HALBERDS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb01.itm~) THEN BEGIN
COPY_EXISTING ~halb01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb02.itm~) THEN BEGIN
COPY_EXISTING ~halb02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb03.itm~) THEN BEGIN
COPY_EXISTING ~halb03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb04.itm~) THEN BEGIN
COPY_EXISTING ~halb03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 255
	SET setg = 182
	SET setb = 189
	SET speed = 0x28
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 255
	SET setg = 182
	SET setb = 189
	SET speed = 0x28
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 33		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb05.itm~) THEN BEGIN
COPY_EXISTING ~halb05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 255
	SET setg = 255
	SET setb = 139
	SET speed = 0x23
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 255
	SET setg = 255
	SET setb = 139
	SET speed = 0x23
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 255
	SET setg = 255
	SET setb = 139
	SET speed = 0x23
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 10		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb06.itm~) THEN BEGIN
COPY_EXISTING ~halb06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb07.itm~) THEN BEGIN
COPY_EXISTING ~halb07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 19	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb08.itm~) THEN BEGIN
COPY_EXISTING ~halb08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb09.itm~) THEN BEGIN
COPY_EXISTING ~halb09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 205
	SET setb = 238
	SET speed = 0x32
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 205
	SET setb = 238
	SET speed = 0x32
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb10.itm~) THEN BEGIN
COPY_EXISTING ~halb10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 199
	SET setg = 33
	SET setb = 36
	SET speed = 0x32
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb11.itm~) THEN BEGIN
COPY_EXISTING ~halb11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 199
	SET setg = 33
	SET setb = 36
	SET speed = 0x32
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~halb12.itm~) THEN BEGIN
COPY_EXISTING ~halb12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 19	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // HAMMERS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm01.itm~) THEN BEGIN
COPY_EXISTING ~hamm01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 40		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm02.itm~) THEN BEGIN
COPY_EXISTING ~hamm02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 40		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm03.itm~) THEN BEGIN
COPY_EXISTING ~hamm03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm04.itm~) THEN BEGIN
COPY_EXISTING ~hamm04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
    WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~ihamm12~
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 32		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 98	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm05.itm~) THEN BEGIN
COPY_EXISTING ~hamm05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm06.itm~) THEN BEGIN
COPY_EXISTING ~hamm06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 91		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm07.itm~) THEN BEGIN
COPY_EXISTING ~hamm07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm08.itm~) THEN BEGIN
COPY_EXISTING ~hamm08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm09.itm~) THEN BEGIN
COPY_EXISTING ~hamm09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 99
	SET setg = 199
	SET setb = 222
	SET speed = 0x32
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm10.itm~) THEN BEGIN
COPY_EXISTING ~hamm10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 96
	SET setg = 160
	SET setb = 192
	SET speed = 0x28
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 96
	SET setg = 160
	SET setb = 192
	SET speed = 0x28
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 96
	SET setg = 160
	SET setb = 192
	SET speed = 0x28
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 51	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm11.itm~) THEN BEGIN
COPY_EXISTING ~hamm11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 96
	SET setg = 160
	SET setb = 192
	SET speed = 0x28
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 96
	SET setg = 160
	SET setb = 192
	SET speed = 0x28
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 96
	SET setg = 160
	SET setb = 192
	SET speed = 0x28
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 51	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~hamm12.itm~) THEN BEGIN
COPY_EXISTING ~hamm12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 50		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // SLINGS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng01.itm~) THEN BEGIN
COPY_EXISTING ~slng01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng02.itm~) THEN BEGIN
COPY_EXISTING ~slng02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 67		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng03.itm~) THEN BEGIN
COPY_EXISTING ~slng03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 40		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng04.itm~) THEN BEGIN
COPY_EXISTING ~slng04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 67		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng05.itm~) THEN BEGIN
COPY_EXISTING ~slng05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 67		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng06.itm~) THEN BEGIN
COPY_EXISTING ~slng06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 67		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng07.itm~) THEN BEGIN
COPY_EXISTING ~slng07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 67		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng08.itm~) THEN BEGIN
COPY_EXISTING ~slng08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 57		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng09.itm~) THEN BEGIN
COPY_EXISTING ~slng09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 57		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~slng10.itm~) THEN BEGIN
COPY_EXISTING ~slng10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 46		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 58	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // SPEARS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper01.itm~) THEN BEGIN
COPY_EXISTING ~sper01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 40		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdgianhl.itm~) THEN BEGIN
COPY_EXISTING ~bdgianhl.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~isper01~
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~csper01~
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 40		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper02.itm~) THEN BEGIN
COPY_EXISTING ~sper02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 93		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsemahl.itm~) THEN BEGIN
COPY_EXISTING ~bdsemahl.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 93		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper03.itm~) THEN BEGIN
COPY_EXISTING ~sper03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper04.itm~) THEN BEGIN
COPY_EXISTING ~sper04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 40		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper05.itm~) THEN BEGIN
COPY_EXISTING ~sper05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 94		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper06.itm~) THEN BEGIN
COPY_EXISTING ~sper06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 94		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper07.itm~) THEN BEGIN
COPY_EXISTING ~sper07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 79	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper08.itm~) THEN BEGIN
COPY_EXISTING ~sper08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 94		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper09.itm~) THEN BEGIN
COPY_EXISTING ~sper09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 94		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper10.itm~) THEN BEGIN
COPY_EXISTING ~sper10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 205
	SET setb = 253
	SET speed = 0x46
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 39		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper11.itm~) THEN BEGIN
COPY_EXISTING ~sper11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 96
	SET setg = 185
	SET setb = 205
	SET speed = 0x46
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 99		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sper12.itm~) THEN BEGIN
COPY_EXISTING ~sper12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 96
	SET setg = 185
	SET setb = 205
	SET speed = 0x46
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 99		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // STAVES
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf01.itm~) THEN BEGIN
COPY_EXISTING ~staf01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf02.itm~) THEN BEGIN
COPY_EXISTING ~staf02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf03.itm~) THEN BEGIN
COPY_EXISTING ~staf03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf05.itm~) THEN BEGIN
COPY_EXISTING ~staf05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf06.itm~) THEN BEGIN
COPY_EXISTING ~staf06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf07.itm~) THEN BEGIN
COPY_EXISTING ~staf07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 98		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 98	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 98	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf08.itm~) THEN BEGIN
COPY_EXISTING ~staf08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 85		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 85	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 85	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf09.itm~) THEN BEGIN
COPY_EXISTING ~staf09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 10		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf10.itm~) THEN BEGIN
COPY_EXISTING ~staf10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf11.itm~) THEN BEGIN // staff of the magi
COPY_EXISTING ~staf11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~istaf12~
	WRITE_LONG  0x5C 0
    WRITE_ASCII 0x58 ~cstaf11~
	WRITE_ASCII 0x44 ~gstaf01~
	WRITE_ASCII 0x22 ~QS~
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = agrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = ateal		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = apink		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = ayellow		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = ared		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 111
	SET setb = 93
	SET speed = 0x14
	SET location = agreen		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf12.itm~) THEN BEGIN
COPY_EXISTING ~staf12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~istaf11~
	WRITE_LONG  0x5C 0
    WRITE_ASCII 0x58 ~cstaf12~
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf13.itm~) THEN BEGIN
COPY_EXISTING ~staf13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 104		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf14.itm~) THEN BEGIN
COPY_EXISTING ~staf14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 39		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf15.itm~) THEN BEGIN
COPY_EXISTING ~staf15.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf16.itm~) THEN BEGIN
COPY_EXISTING ~staf16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 39		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf17.itm~) THEN BEGIN
COPY_EXISTING ~staf17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 10		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf18.itm~) THEN BEGIN
COPY_EXISTING ~staf18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 39		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf19.itm~) THEN BEGIN
COPY_EXISTING ~staf19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 139
	SET setb = 202
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 139
	SET setb = 202
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 139
	SET setb = 202
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf20.itm~) THEN BEGIN
COPY_EXISTING ~staf20.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 139
	SET setb = 202
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 139
	SET setb = 202
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 139
	SET setb = 202
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf21.itm~) THEN BEGIN
COPY_EXISTING ~staf21.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 36		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 36	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf22.itm~) THEN BEGIN
COPY_EXISTING ~staf22.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 36		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 36	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf23.itm~) THEN BEGIN
COPY_EXISTING ~staf23.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 192
	SET setb = 0
	SET speed = 0x28
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 192
	SET setb = 0
	SET speed = 0x28
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 53		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 52	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~staf24.itm~) THEN BEGIN
COPY_EXISTING ~staf24.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 39		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // SWORDS, ONE HANDED
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h01.itm~) THEN BEGIN
COPY_EXISTING ~sw1h01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h02.itm~) THEN BEGIN
COPY_EXISTING ~sw1h02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 50		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h03.itm~) THEN BEGIN
COPY_EXISTING ~sw1h03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 60		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 45	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 59	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h04.itm~) THEN BEGIN
COPY_EXISTING ~sw1h04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h05.itm~) THEN BEGIN
COPY_EXISTING ~sw1h05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 6		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h06.itm~) THEN BEGIN
COPY_EXISTING ~sw1h06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 50		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 6	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h07.itm~) THEN BEGIN
COPY_EXISTING ~sw1h07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h08.itm~) THEN BEGIN
COPY_EXISTING ~sw1h08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 74	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h09.itm~) THEN BEGIN
COPY_EXISTING ~sw1h09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h10.itm~) THEN BEGIN
COPY_EXISTING ~sw1h10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 57
	SET setg = 0
	SET setb = 0
	SET speed = 0x2d
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 76	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 6	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h12.itm~) THEN BEGIN
COPY_EXISTING ~sw1h12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h14.itm~) THEN BEGIN
COPY_EXISTING ~sw1h14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 74	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h16.itm~) THEN BEGIN
COPY_EXISTING ~sw1h16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 75
	SET setb = 114
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h17.itm~) THEN BEGIN
COPY_EXISTING ~sw1h17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h18.itm~) THEN BEGIN
COPY_EXISTING ~sw1h18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h19.itm~) THEN BEGIN
COPY_EXISTING ~sw1h19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 6		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h20.itm~) THEN BEGIN
COPY_EXISTING ~sw1h20.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h22.itm~) THEN BEGIN
COPY_EXISTING ~sw1h22.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h23.itm~) THEN BEGIN
COPY_EXISTING ~sw1h23.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 12		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 90	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 61	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h24.itm~) THEN BEGIN
COPY_EXISTING ~sw1h24.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred	// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 12		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h26.itm~) THEN BEGIN
COPY_EXISTING ~sw1h26.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h27.itm~) THEN BEGIN
COPY_EXISTING ~sw1h27.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h28.itm~) THEN BEGIN
COPY_EXISTING ~sw1h28.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h29.itm~) THEN BEGIN
COPY_EXISTING ~sw1h29.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 49		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 57	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h30.itm~) THEN BEGIN
COPY_EXISTING ~sw1h30.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 90		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h31.itm~) THEN BEGIN
COPY_EXISTING ~sw1h31.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 160
	SET setb = 191
	SET speed = 0x3f97
	SET location = wgrey		// location
	SET setr = 255
	SET setg = 225
	SET setb = 53
	SET speed = 0x3c
	SET location = wred		// location
	SET setr = 255
	SET setg = 225
	SET setb = 53
	SET speed = 0x3c
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h32.itm~) THEN BEGIN
COPY_EXISTING ~sw1h32.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 255
	SET setg = 146
	SET setb = 189
	SET speed = 0x78
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 47		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h34.itm~) THEN BEGIN
COPY_EXISTING ~sw1h34.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 57	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h35.itm~) THEN BEGIN
COPY_EXISTING ~sw1h35.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 99	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h37.itm~) THEN BEGIN
COPY_EXISTING ~sw1h37.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 55		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 55	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 103	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h38.itm~) THEN BEGIN
COPY_EXISTING ~sw1h38.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 59		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 57	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h40.itm~) THEN BEGIN
COPY_EXISTING ~sw1h40.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 46		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h41.itm~) THEN BEGIN
COPY_EXISTING ~sw1h41.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h42.itm~) THEN BEGIN
COPY_EXISTING ~sw1h42.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h43.itm~) THEN BEGIN
COPY_EXISTING ~sw1h43.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h44.itm~) THEN BEGIN
COPY_EXISTING ~sw1h44.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h45.itm~) THEN BEGIN
COPY_EXISTING ~sw1h45.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 16		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h48.itm~) THEN BEGIN
COPY_EXISTING ~sw1h48.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 100	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h49.itm~) THEN BEGIN
COPY_EXISTING ~sw1h49.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 30		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 100	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h51.itm~) THEN BEGIN // celestial fury
COPY_EXISTING ~sw1h51.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 229
	SET setg = 238
	SET setb = 103
	SET speed = 0x5a
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h52.itm~) THEN BEGIN
COPY_EXISTING ~sw1h52.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 36		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h53.itm~) THEN BEGIN
COPY_EXISTING ~sw1h53.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 12		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
 
 ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h55.itm~) THEN BEGIN
COPY_EXISTING ~sw1h55.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h56.itm~) THEN BEGIN
COPY_EXISTING ~sw1h56.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h60.itm~) THEN BEGIN // angurvadal
COPY_EXISTING ~sw1h60.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 12		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h61.itm~) THEN BEGIN // angurvadal
COPY_EXISTING ~sw1h61.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 12		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h62.itm~) THEN BEGIN
COPY_EXISTING ~sw1h62.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 51		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h63.itm~) THEN BEGIN
COPY_EXISTING ~sw1h63.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 96		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 51		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h64.itm~) THEN BEGIN
COPY_EXISTING ~sw1h64.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 172
	SET setg = 36
	SET setb = 26
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 51		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h65.itm~) THEN BEGIN
COPY_EXISTING ~sw1h65.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 172
	SET setg = 36
	SET setb = 26
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 97		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 51		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 97	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
 
 ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h71.itm~) THEN BEGIN
COPY_EXISTING ~sw1h71.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 46		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h75.itm~) THEN BEGIN
COPY_EXISTING ~sw1h75.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 16	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h76.itm~) THEN BEGIN
COPY_EXISTING ~sw1h76.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h77.itm~) THEN BEGIN // angurvadal
COPY_EXISTING ~sw1h77.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET speed = 0x14
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25		// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdskgr05.itm~) THEN BEGIN
COPY_EXISTING ~bdskgr05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 64
	SET setg = 0
	SET setb = 0
	SET location = ablue		// location
	LAUNCH_PATCH_MACRO ~glow~
	SET setr = 0
	SET setg = 0
	SET setb = 0
	SET location = wred	// location
	LAUNCH_PATCH_MACRO ~glow~
	SET gradient = 12		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 115	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw1h13.itm~) THEN BEGIN
COPY_EXISTING ~bdsw1h13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~isw1h09~
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw1h24.itm~) THEN BEGIN
COPY_EXISTING ~bdsw1h24.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~isw1h09~
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 93	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw1h19.itm~) THEN BEGIN
COPY_EXISTING ~bdsw1h19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	WRITE_LONG  0x3E 0
    WRITE_ASCII 0x3A ~isw1h07~
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw1h26.itm~) THEN BEGIN
COPY_EXISTING ~bdsw1h26.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 22	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw1hel.itm~) THEN BEGIN
COPY_EXISTING ~bdsw1hel.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 6		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw1hgh.itm~) THEN BEGIN
COPY_EXISTING ~bdsw1hgh.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 74	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~ohhshim.itm~) THEN BEGIN
COPY_EXISTING ~ohhshim.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 99		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 94	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // SWORDS, TWO HANDED
 
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h01.itm~) THEN BEGIN
COPY_EXISTING ~sw2h01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 24		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 24	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 5	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h02.itm~) THEN BEGIN
COPY_EXISTING ~sw2h02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h03.itm~) THEN BEGIN
COPY_EXISTING ~sw2h03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h07.itm~) THEN BEGIN
COPY_EXISTING ~sw2h07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 66
	SET setg = 39
	SET setb = 96
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 28		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 66	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 65	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h10.itm~) THEN BEGIN // carsomyr
COPY_EXISTING ~sw2h10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 225
	SET setg = 212
	SET setb = 0
	SET speed = 0x32
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h11.itm~) THEN BEGIN
COPY_EXISTING ~sw2h11.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 61		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h12.itm~) THEN BEGIN
COPY_EXISTING ~sw2h12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 179
	SET setg = 156
	SET setb = 212
	SET speed = 0x64
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 60		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 60	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h15.itm~) THEN BEGIN
COPY_EXISTING ~sw2h15.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h17.itm~) THEN BEGIN
COPY_EXISTING ~sw2h17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 235
	SET setg = 242
	SET setb = 0
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h18.itm~) THEN BEGIN
COPY_EXISTING ~sw2h18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 235
	SET setg = 242
	SET setb = 0
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h19.itm~) THEN BEGIN // carsomyr +6
COPY_EXISTING ~sw2h19.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET setr = 235
	SET setg = 242
	SET setb = 0
	SET speed = 0x1e
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~pulse~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h20.itm~) THEN BEGIN
COPY_EXISTING ~sw2h20.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 29		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 58	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~bdsw2hgh.itm~) THEN BEGIN
COPY_EXISTING ~bdsw2hgh.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  // CROSSBOWS
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow01.itm~) THEN BEGIN
COPY_EXISTING ~xbow01.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 40	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 28	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow02.itm~) THEN BEGIN
COPY_EXISTING ~xbow02.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 31		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow03.itm~) THEN BEGIN
COPY_EXISTING ~xbow03.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 25		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 29	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 25	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow04.itm~) THEN BEGIN
COPY_EXISTING ~xbow04.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 9	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 10	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow05.itm~) THEN BEGIN
COPY_EXISTING ~xbow05.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow06.itm~) THEN BEGIN
COPY_EXISTING ~xbow06.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 100		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 27	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 30	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow07.itm~) THEN BEGIN
COPY_EXISTING ~xbow07.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 6		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 6	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow08.itm~) THEN BEGIN
COPY_EXISTING ~xbow08.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 50		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow09.itm~) THEN BEGIN
COPY_EXISTING ~xbow09.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 95		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 39	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 95	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow10.itm~) THEN BEGIN
COPY_EXISTING ~xbow10.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 92		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 96	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 92	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow12.itm~) THEN BEGIN
COPY_EXISTING ~xbow12.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 104		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 26	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 104	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow13.itm~) THEN BEGIN
COPY_EXISTING ~xbow13.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 95		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 61	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 61	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow14.itm~) THEN BEGIN
COPY_EXISTING ~xbow14.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 38		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 33	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 23	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow15.itm~) THEN BEGIN
COPY_EXISTING ~xbow15.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 46	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow16.itm~) THEN BEGIN
COPY_EXISTING ~xbow16.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 27		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 46	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 47	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow17.itm~) THEN BEGIN
COPY_EXISTING ~xbow17.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 31		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END
  
  ACTION_IF (FILE_EXISTS_IN_GAME ~xbow18.itm~) THEN BEGIN
COPY_EXISTING ~xbow18.itm~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
	LAUNCH_PATCH_MACRO ~clear~
	SET gradient = 44		// colour index
	SET location = wgrey		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 46	// colour index
	SET location = wred		// location
	LAUNCH_PATCH_MACRO ~colour~
	SET gradient = 50	// colour index
	SET location = wblue		// location
	LAUNCH_PATCH_MACRO ~colour~
   END
   BUT_ONLY
  END